title: Geoveza
author: Geoveza
email: halo@geoveza.me
description: > # this means to ignore newlines until "show_exerpts:"
  Let's Grasp Your Ability to Learn Exploit and Code . 
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Geoveza
  tagline: IT Researcher
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: geoveza1
    github:  Geoveza
    linkedIn: in/eza-geoveza-637811158/
    # dribbble: 
    facebook: eza.geovezaa
    rss: rss
    # flickr:   
    # instagram: 
    # linkedin: 
    # pinterest: 
    # youtube: 
    # youtube_channel: -
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed